# Generated by Django 5.0.4 on 2024-04-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("company", models.CharField(max_length=255)),
                ("adref", models.CharField(max_length=255)),
                ("created", models.DateTimeField()),
                ("contract_type", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=255)),
                ("job_class", models.CharField(db_column="__CLASS__", max_length=255)),
                ("contract_time", models.CharField(max_length=50)),
                ("redirect_url", models.URLField(max_length=1024)),
                ("salary_is_predicted", models.BooleanField()),
                ("description", models.TextField()),
                ("country", models.CharField(max_length=50)),
                ("salary_max", models.DecimalField(decimal_places=2, max_digits=10)),
                ("salary_min", models.DecimalField(decimal_places=2, max_digits=10)),
                ("category", models.CharField(max_length=255)),
            ],
        ),
    ]
