# Generated by Django 5.0.4 on 2024-04-06 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=100)),
                ("label", models.CharField(max_length=255)),
                ("class_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(max_length=255)),
                ("class_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area", models.JSONField()),
                ("display_name", models.CharField(max_length=255)),
                ("class_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("adref", models.CharField(max_length=255)),
                ("created", models.DateTimeField()),
                ("contract_type", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=255)),
                ("job_class", models.CharField(db_column="__CLASS__", max_length=255)),
                ("contract_time", models.CharField(max_length=50)),
                ("redirect_url", models.URLField(max_length=1024)),
                ("salary_is_predicted", models.BooleanField()),
                ("description", models.TextField()),
                ("salary_max", models.DecimalField(decimal_places=2, max_digits=10)),
                ("salary_min", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="job.category"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="job.company"
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="job.location"
                    ),
                ),
            ],
        ),
    ]
