# Generated by Django 5.0.4 on 2024-04-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0003_alter_job_latitude_alter_job_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="salary_max",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="salary_min",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=10, null=True
            ),
        ),
    ]
